### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by AnnoyedDev** [Hqndler/InstantPaddleVideOCR#1]

**Comment by Hqndler** [comment]
Zǎo shang hǎo zhōng guó!
Xiàn zài wǒ yǒu bing chilling
Wǒ hěn xǐ huān bing chilling
Dàn shì "sù dù yǔ jī qíng jiǔ" bǐ bing chilling

**Comment by MagikarpLaCarpe** [comment]
https://www.youtube.com/shorts/EP-12TC4MHk
